#!/usr/bin/env ruby
require 'fileutils'
vim_dir = File.absolute_path(File.dirname(__FILE__))

Dir[vim_dir + "/bundle/*"].each do |directory|
  FileUtils.cd directory
  puts "Updating #{directory}..."
  puts `git fetch origin; git rebase origin/master`
  FileUtils.cd(vim_dir)
end
